### ISSUE TITLE
Brass and Thaumium recipe not working with Thaumic Periphery installed

### ISSUE THREAD

**Issue by angelnc1989** [the-realest-stu/Thaumic-Periphery#10]
https://github.com/Azanor/thaumcraft-beta/issues/1147

I wanted to report it on Azanors issue tracker, but this lead me here.
The Crucible recipes for Brass and Thaumium don't work at all with Thaumic Periphery installed.

**Comment by wamc2017** [comment]
Thaumic Periphery only changes the Brass recipe from Iron to copper, it doesn't alter the Thaumium recipe, so only Brass should be affected. 
Which version of Thaumcraft and Thaumic Periphery are you using? Have you unlocked the knowledge in the book before trying to create Brass and Thaumium? A modlist would help as well maybe...

**Comment by angelnc1989** [comment]
The Copper thing explains it. I don't have Copper in my modpack.
[Here](https://pastebin.com/kiZzu54A) is the modlist.
Thaumcraft is on version 6.1 beta 23 and Thaumic Periphery on 0.2.4, but the issue was there on the prior Thaumcraft version.

**Comment by wamc2017** [comment]
The copper thing could be turned of in the config (B:"Copper Brass Recipe"=false). Does it work, if you turn it of?

**Comment by angelnc1989** [comment]
Setting it to false fixes both recipes.
