### ISSUE TITLE
1.12.2: thaumicperiphery-0.2.2 Client Crash

### ISSUE THREAD

**Issue by MachinegunMarty** [the-realest-stu/Thaumic-Periphery#2]
Hey There the-realest-stu,

Is was trying to make an "Cursed Lasso",from Extra Utilities 2, from my inventory and my client crashed.
My server was fine.
I started up again and tried again to make the Lasso, but this time in an tinkers crafting table... Client Crash
I started up again and tried again to make the Lasso, but this time in an Vanilla Crafting table.. put the golden lasso in .... crash.

I have removed "Thaumic Periphery" and now i was able to make the Cursed Lasso without a problem.

i've attached the crash log.

[crash-2018-05-19_20.19.42-client-Vanilla.txt](https://github.com/the-realest-stu/Thaumic-Periphery/files/2019736/crash-2018-05-19_20.19.42-client-Vanilla.txt)

If you need more information, just ask.

grtz,

Machinegun Marty

**Comment by the-realest-stu** [comment]
I just uploaded a new build to curseforge that should fix this issue. It should be available soon (maximum of a few hours, but at this time of day I'd expect it to be much less).
